import React from 'react';
import { AlertTriangle } from 'lucide-react';

export const DisclaimerBanner = () => {
  return (
    <div className="bg-amber-50 border-l-4 border-amber-500 text-amber-900 p-3.5 mb-6 text-sm flex items-center justify-between rounded-r shadow-sm">
      <div className="flex items-center gap-2.5">
        <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
        <div>
          <span className="font-semibold">Screening Tool Disclaimer:</span> Flags generated by Kosh-Drishti represent statistical & rule-based screening indicators, not a definitive legal or fraud verdict. All flagged works require human audit verification.
        </div>
      </div>
      <span className="text-xs bg-amber-100 text-amber-800 font-mono px-2 py-0.5 rounded border border-amber-300">
        SRS BR-05 Enforced
      </span>
    </div>
  );
};
